version: "3.7"

services:

        djangoapp:
                # build: ./djangoapp
                image: rohitchorpa32/django-docker:latest
                container_name: djangoapp
                restart: always
                expose:
                        - 8000
                depends_on:
                        - db
                        - redis
        djangosocket:
                # build: ./djangoapp
                image: rohitchorpa32/django-docker:latest
                container_name: djangosocket
                restart: always
                expose:
                        - 8010
                command: python djangoproject/manage.py runserver 0.0.0.0:8010
                depends_on:
                        - db
                        - redis
                        - djangoapp

        nginx:
                image: rohitchorpa32/nginx-docker:latest
                # build: ./nginx
                container_name: nginx
                restart: always
                ports:
                        - "80:80"
                depends_on:
                        - djangoapp
                        - djangosocket
        db:
                # build: ./postgresql
                image: rohitchorpa32/postgres-docker:latest
                container_name: postgres
                restart: always

        redis:
                image: redis
                container_name: redis
                restart: always

